plugins {
    id 'com.android.library'
}

group = 'com.vladih.computer_vision.flutter_vision'
version = '1.0'

android {
    namespace 'com.vladih.computer_vision.flutter_vision'
    compileSdk = 34

    defaultConfig {
        minSdk = 21
        targetSdk = 34
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    aaptOptions {
        noCompress 'tflite'
        noCompress 'lite'
    }

    buildFeatures {
        mlModelBinding = true
    }

    sourceSets {
        main {
            java.srcDirs = ['src/main/java']
            resources.srcDirs = ['src/main/res']
        }
    }
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' } // مهم
}

dependencies {
    // النسخة الموجودة فعليًا على JitPack
    implementation 'com.github.vladiH:opencv-android:v1.0.0'

    implementation 'com.google.ai.edge.litert:litert:1.4.0'
    implementation 'com.google.ai.edge.litert:litert-api:1.4.0'
    implementation 'com.google.ai.edge.litert:litert-gpu:1.4.0'
    implementation 'com.google.ai.edge.litert:litert-gpu-api:1.4.0'
    implementation 'com.google.ai.edge.litert:litert-support:1.4.0'
    implementation 'com.google.ai.edge.litert:litert-metadata:1.4.0'
}
